### ISSUE TITLE
Dataset Json File

### ISSUE THREAD

**Issue by chuanyang-Zheng** [sahsaeedi/TPO#1]
Thank you very much for your great work. If possible, could you please share the dataset json file?

Again, thank you very much for your attention, and looking forward to hearing from you.

**Comment by sahsaeedi** [comment]
Hi Chuanyang,

We used the Ultra-Feedback dataset. You can load the dataset from HuggingFace and use any three preferences that work for you. If you want to use the data we used exactly, I suggest you read the experiment section of the paper.

Link of the dataset: https://huggingface.co/datasets/openbmb/UltraFeedback
